client_server_channel/controls/products/__init__.py
from .categories import CategoriesC
from .product_info import ProductInfoC
from .dealer import DealerC
from .product_status import ProductStatusC
from .product import ProductC
from .firmware import FirmwareC
from .product_photo import ProductPhotoC

client_server_channel/models/products/__init__.py
from .categories import CategoriesTable
from .product_info import ProductInfoTable
from .dealer import DealerTable
from .product_status import ProductStatusTable
from .product import ProductTable
from .firmware import FirmwareTable
from .product_photo import ProductPhotoTable

client_server_channel/views/products/__init__.py
from .views import products

client_server_channel/views/products/views.py
from flask import Blueprint, render_template, request, url_for, redirect, session
from client_server_channel.controls import (ProductC, ProductInfoC, ProductPhotoC,
						DealerC, ClientC, FirmwareC, ProductStatusC)
from .. import view_utils as utls
from .category import category
from .product_info import product_info
from .dealer import dealer
from .status import status
from .firmware import firmware
from .product_photo import product_photo
# dushanbagacha commit

products = Blueprint('products', __name__, url_prefix='/products')
products.register_blueprint(category)
products.register_blueprint(product_info)
products.register_blueprint(dealer)
products.register_blueprint(status)
products.register_blueprint(firmware)
products.register_blueprint(product_photo)

@products.route('/')
def products_page():
	if not 'username' in session:
		return redirect(url_for('employees.login'))

	return render_template(
		utls.url_join(['products', 'products.html'])
	)

@products.route('/products')
def product_list():
	return render_template(utls.url_join(['products','products.html']))


@products.route('/product/<int:pid>')
def product_page(pid):
	return render_template(utls.url_join(['products','product.html']))


@products.route('/add', methods=['GET', 'POST'])
def add():
	if not 'username' in session:
		return redirect(url_for('employees.login'))

	if request.method == 'GET':

		return render_template(
			utls.url_join(['products', 'add.html']),
			products_ids = ProductInfoC.get_ids_names(),
			dealers_ids = DealerC.get_ids_names(),
			firmwares_ids = FirmwareC.get_ids_names(),
			status_ids = ProductStatusC.get_ids_names()
		)

	if request.method == 'POST':
		params = request.form
		result = ProductC.add({
			'product_id' : params['product_id'],
			'mac_address' : params['mac_address'],
			'dealer_id' : params['dealer_id'],
			'manufactured_date' : params['manufactured_date'],
			'firmware_id' : params['fw_id'],
			'status_id' : params['status_id'],
			'resp_emp_id' : session['employee']['id'],
			'add_emp_id' : session['employee']['id'],
			'modify_emp_id' : session['employee']['id']
		})

		if result['success']:
			return redirect(url_for('products.all'))

		return result


@products.route('/get/<serial_num>')
def get(serial_num):
	if not 'username' in session:
		return redirect(url_for('employees.login'))

	product_info = ProductC.get(serial_num)
	
	if len(product_info['data']) > 0:
		
		return render_template(
			utls.url_join(['products', 'get.html']),
			product_info = product_info,
			product_name = ProductInfoC.get(product_info['data']['product_id']),
			dealer_name = DealerC.get(product_info['data']['dealer_id']),
			client_name = ClientC.get(product_info['data']['client_id']),
			firmware_name = FirmwareC.get(product_info['data']['firmware_id']),
			status_name = ProductStatusC.get(product_info['data']['status_id']),
			product_photo = ProductPhotoC.get_by_product_id(product_info['data']['product_id'])
		)

	return redirect(url_for('products.all'))


@products.route('/all')
def all():
	if not 'username' in session:
		return redirect(url_for('employees.login'))

	products_info = ProductC.get_all()

	if products_info['success']:
		if len(products_info['data']) > 0:
			return render_template(
				utls.url_join(['products', 'all.html']),
				products_info = products_info,
				products_by_ids = ProductInfoC.get_names_by_ids(products_info['data']['product_id']),
				dealers_by_ids = DealerC.get_names_by_ids(products_info['data']['dealer_id']),
				clients_by_ids = ClientC.get_names_by_ids(products_info['data']['client_id']),
				firmwares_by_ids = FirmwareC.get_names_by_ids(products_info['data']['firmware_id']),
				status_by_ids = ProductStatusC.get_names_by_ids(products_info['data']['status_id'])
			)

		return render_template(utls.url_join(['products', 'all.html']),
			products_info = products_info
		)

	return redirect(url_for('core.index'))


@products.route('/update/<serial_num>', methods=['GET', 'POST'])
def update(serial_num):
	if not 'username' in session:
		return redirect(url_for('employees.login'))

	if request.method == 'GET':
		product_info = ProductC.get(serial_num)
	
		if len(product_info['data']) > 0:
			return render_template(
				utls.url_join(['products', 'update.html']),
				product_info = product_info,
				dealers_ids = DealerC.get_ids_names(),
				status_ids = ProductStatusC.get_ids_names(),
				product_name = ProductInfoC.get(product_info['data']['product_id']),
				firmwares_ids = FirmwareC.get(product_info['data']['firmware_id']),
			)

		return redirect(url_for('products.all'))

	if request.method == 'POST':
		params = request.form
		result = ProductC.update({
			'dealer_id' : params['dealer_id'],
			'resp_emp_id' : session['employee']['id'],
			'status_id' : params['status_id'],
			'modify_emp_id' : session['employee']['id'],
			'serial_num' : serial_num
		})

		if result['success']:
			return redirect(url_for('products.all'))

		return result


@products.route('/delete/<serial_num>', methods=['DELETE'])
def delete(serial_num):
	if not 'username' in session:
		return redirect(url_for('employees.login'))

	return ProductC.delete(serial_num)

client_server_channel/templates/products/add.html
{% extends 'base.html' %}

{% block head %}
<title>Новый продукт</title>
{{super()}}

<link rel="stylesheet" href="/static/css/products/products_base.css">
<link rel="stylesheet" href="/static/css/products/add.css">


{% endblock %}

{% block body %}
{{super()}}

<div class="add-container">
    <div class="add-header">
        <h3>Новый продукт</h3>
    </div>

    <form id="myForm" class="add-form">

        <div class="form-control">
            <label for="product_id">Название продукта</label><span class="star">*</span>
            <select name="product_id" id="product_id" required>
                <option hidden value="" selected disabled>--Выбрать--</option>
                {% for i in range(products_ids['data']['product_id']|length)%}
                <option value="{{products_ids['data']['product_id'][i]}}">{{products_ids['data']['name'][i]}}</option>
                {%endfor%}
            </select>


            <label for="dealer_id">Дилер</label><span class="star">*</span>
            <select name="dealer_id" id="dealer_id" required>
                <option hidden value="" selected disabled>--Выбрать--</option>
                {% for i in range(dealers_ids['data']['dealer_id']|length)%}
                <option value="{{dealers_ids['data']['dealer_id'][i]}}">{{dealers_ids['data']['name'][i]}}</option>
                {%endfor%}
            </select>
            
            <label for="mac_address">МАС адрес</label>
            <input type="text" name="mac_address" id="mac_address" placeholder="Введите mac адрес...">

        </div>


        <div class="form-control">
            <label for="manufactured_date">Дата изготовления</label><span class="star">*</span>
            <input type="date" name="manufactured_date" id="manufactured_date" required>

            <label for="fw_id">Прощивка</label><span class="star">*</span>
            <select name="fw_id" id="fw_id" required>
                <option hidden value="" selected disabled>--Выбрать--</option>
                {% for i in range(firmwares_ids['data']['fw_id']|length)%}
                <option value="{{firmwares_ids['data']['fw_id'][i]}}">{{firmwares_ids['data']['name'][i]}}</option>
                {%endfor%}
            </select>


            <label for="status_id">Статус</label><span class="star">*</span>
            <select name="status_id" id="status_id" required>
                <option hidden value="" selected disabled>--Выбрать--</option>
                {% for i in range(status_ids['data']['status_id']|length)%}
                <option value="{{status_ids['data']['status_id'][i]}}">{{status_ids['data']['status'][i]}}</option>
                {%endfor%}
            </select>

        </div>


        <input type="submit" class="add-submit" value="Сохранить"/><br>

        <button type="button" onclick="otmenFunction()" class="add-submit2" value="Отмена"> Отмена</button>

    </form>
</div>


<script src="/static/js/products/add.js"></script>

{% endblock %}

client_server_channel/templates/products/all.html
{% extends 'base.html' %}

{% block head %}
<title>Продукты</title>
{{super()}}

<link rel="stylesheet" href="/static/css/products/all.css">

{% endblock %}

{% block body %}
{{super()}}

<div class="add-button">
    <a class="back-button" href="{{url_for('products.products_page')}}">Назад</a>
    <button id="addClick">Добавить</button>
</div>
<h2 class="header-all">Продукты</h2>
<div class="table">
    <table>
        <thead>

        <tr>

            <th class="hidden">ИД</th>

            <th>Серийный номер</th>

            <th>Название</th>

            <th>Дилер</th>

            <th>MAC-адрес</th>

            <th>Логин клиента</th>

            <th>ID клиента</th>

            <th>Клиент</th>

            <th>Прощивка</th>

            <th>Статус</th>

            <th>Действие</th>

        </tr>

        </thead>


        <tbody id="tBody">

        {% for i in range(products_info['data']['serial_num']|length) %}
        <tr ondblclick="getType(this)" ser_num="{{products_info['data']['serial_num'][i]}}">

            <td >{{products_info['data']['serial_num'][i]}}</td>

            <td>{{products_by_ids['data'][products_info['data']['product_id'][i]]}}</td>

            <td>{{dealers_by_ids['data'][products_info['data']['dealer_id'][i]]}}</td>

            <td>{{products_info['data']['mac_address'][i]}}</td>

            <td>{{clients_by_ids['data']['usernames'][products_info['data']['client_id'][i]]}}</td>

            <td>{{products_info['data']['client_id'][i]}}</td>

            <td>{{clients_by_ids['data']['fullnames'][products_info['data']['client_id'][i]]}}</td>

            <td>{{firmwares_by_ids['data'][products_info['data']['firmware_id'][i]]}}</td>

            <td>{{status_by_ids['data'][products_info['data']['status_id'][i]]}}</td>

            <td>
                <button onclick="deleteType(this)">Удалить</button>
            </td>

        </tr>
        {% endfor %}

        </tbody>

    </table>
</div>

<script src="/static/js/products/all.js"></script>

{% endblock %}

client_server_channel/templates/products/get.html
{% extends 'base.html' %}

{% block head %}
<title>Информация о продукте</title>
{{super()}}

<link rel="stylesheet" href="/static/css/products/products_base.css">
<link rel="stylesheet" href="/static/css/products/get.css">

{% endblock %}

{% block body %}
{{super()}}

<div style="position:relative;">
    <div class="add-container">
        <div class="add-header">
            <h3>Информация о продукте</h3>
        </div>

        <div class="add-form" id="myForm">

            <input type="hidden" id="product_id" value="{{product_info['data']['serial_num']}}">


            <div class="form-control">

                <label for="default_login">Логин по умолчанию</label>
                <input type="text" id="default_login" readonly
                       value="{{product_info['data']['default_login']}}">

                <label for="default_password">Пароль по умолчанию</label>
                <input type="text" id="default_password" readonly
                       value="{{product_info['data']['default_password']}}">

                <label for="ap_login">Wi-Fi Логин</label>
                <input type="text" id="ap_login" readonly
                       value="{{product_info['data']['ap_login']}}">

                <label for="ap_password">Wi-Fi Пароль</label>
                <input type="text" id="ap_password" readonly
                       value="{{product_info['data']['ap_password']}}">

            </div>

            <div class="form-control">
                <label for="serial_num">Серийный номер</label>
                <input type="text" id="serial_num" readonly
                       value="{{product_info['data']['serial_num']}}">

                <label for="manufactured_date">Дата</label>
                <input type="date" id="manufactured_date" readonly
                       value="{{product_info['data']['manufactured_date']}}">

                <label for="product_name">Название</label>
                <input type="text" id="product_name" readonly
                       value="{{product_name['data']['name']}}">


                <label for="dealer_name">Дилер</label>
                <input type="text" id="dealer_name" readonly
                       value="{{dealer_name['data']['name']}}">
            </div>


            <div class="form-control">
                <label for="mac_address">MAC-адрес</label>
                <input type="text" id="mac_address" readonly
                       value="{{product_info['data']['mac_address']}}">

                <label for="firmware_name">Прощивка</label>
                <input type="text" id="firmware_name" readonly
                       value="{{firmware_name['data']['name']}}">

                <label for="status_name">Статус</label>
                <input type="text" id="status_name" readonly
                       value="{{status_name['data']['status']}}">

                <label for="client_id">ID клиента </label>
                <input type="text" id="client_id" readonly
                       value="{{client_name['data']['client_id']}}">

            </div>

            <div class="form-control">
                <label for="username">Логин клиента</label>
                <input type="text" id="username" readonly
                       value="{{client_name['data']['username']}}">

                <label for="client_name">Клиент</label>
                <input type="text" id="client_name" readonly
                       value="{{client_name['data']['last_name']}} {{client_name['data']['first_name']}} {{client_name['data']['middle_name']}}">

            </div>

            <div class="div-buttons">
                <button onclick="updateProduct()" class="add-submit">
                    Изменить
                </button>

                <button onclick="deleteProduct()" class="add-submit2">
                    Удалить
                </button>

                <button onclick="otmenFunction()" class="add-submit3">
                    Назад
                </button>
            </div>
        </div>


    </div>
</div>

<script src="/static/js/products/get.js"></script>

{% endblock %}

client_server_channel/templates/products/product.html
{% extends 'base.html' %}

{% block head %}
{{super()}}

<link rel="stylesheet" href="static/css/products/product.css">

{% endblock %}

{% block body %}
{{super()}}

<h1>product page</h1>

<script scr="static/js/products/product.js"></script>

{% endblock %}

client_server_channel/templates/products/products.html
{% extends 'base.html' %}

{% block head %}
{{super()}}
    <link rel="stylesheet" href="/static/css/products/products.css">
{% endblock %}

{% block body %}
{{super()}}

<div style="width: 100%; text-align: center; margin-top: 1%;">
    <h1>Продукты</h1>
</div>

<div class="menu">

    <ul>
        <li><a href="{{url_for('products.category.all')}}">Категории продуктов</a></li>
        <li><a href="{{url_for('products.dealer.all')}}">Дилеры</a></li>
        <li><a href="{{url_for('products.firmware.all')}}">Прошивки устройств</a></li>
        <li><a href="{{url_for('products.product_info.all')}}">Общая информация о продуктов</a></li>
        <li><a href="{{url_for('products.status.all')}}">Статусы продуктов</a></li>
        <li><a href="{{url_for('products.all')}}">Продукты</a></li>
        <li><a href="{{url_for('employees.account')}}" class="back-li">Назад</a></li>
    </ul>

</div>


<script src="/static/js/products/products.js"></script>
{% endblock %}

client_server_channel/templates/products/update.html
{% extends 'base.html' %}

{% block head %}
<title>Изменить данные продукта</title>
{{super()}}

<link rel="stylesheet" href="/static/css/products/products_base.css">
<link rel="stylesheet" href="/static/css/products/update.css">

{% endblock %}

{% block body %}
{{super()}}

<div class="add-container">

    <div class="add-header">
        <h3>Изменить данные продукта</h3>
    </div>

    <form action="{{ url_for('products.update', serial_num=product_info['data']['serial_num']) }}"
          method="POST"
          id="myForm" class="add-form">

        <div class="form-control">

            <label for="dealers_ids">Дилер</label>
            <select name="dealer_id" id="dealers_ids" required>
                {%for i in range(dealers_ids['data']['dealer_id']|length)%}
                {%if product_info['data']['dealer_id'] == dealers_ids['data']['dealer_id'][i]%}
                <option selected value="{{dealers_ids['data']['dealer_id'][i]}}">
                    {{dealers_ids['data']['name'][i]}}
                </option>
                {% else %}
                <option value="{{dealers_ids['data']['dealer_id'][i]}}">
                    {{dealers_ids['data']['name'][i]}}
                </option>
                {%endif%}
                {%endfor%}
            </select>

        </div>

        <div class="form-control">

            <label for="status_ids">Статус</label>
            <select name="status_id" id="status_ids" required>
                {%for i in range(status_ids['data']['status_id']|length)%}
                {%if product_info['data']['status_id'] == status_ids['data']['status_id'][i]%}
                <option selected value="{{status_ids['data']['status_id'][i]}}">
                    {{status_ids['data']['status'][i]}}
                </option>
                {% else %}
                <option value="{{status_ids['data']['status_id'][i]}}">
                    {{status_ids['data']['status'][i]}}
                </option>
                {%endif%}
                {%endfor%}
            </select>

        </div>


        <input type="submit" class="add-submit" value="Сохранить"/>

        <button type="button" onclick="otmenFunction()" class="add-submit2" value="Add">
            Отмена
        </button>

    </form>

</div>


<script src="/static/js/products/update.js"></script>

{% endblock %}