client_server_channel/controls/sp_logistic/__init__.py
from .sp_logistic import SpLogisticC

client_server_channel/models/sp_logistic/__init__.py
from .sp_logistic import SpLogisticTable

client_server_channel/views/sp_logistic/__init__.py
from .views import sp_logistic

client_server_channel/views/sp_logistic/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from client_server_channel.controls import (SpLogisticC, CarrierC, CurrencyC,
                                            ShippingTypeC, TrackingStatusC)
from .. import view_utils as utls


sp_logistic = Blueprint('sp_logistic', __name__, url_prefix='/sp_logistic')


@sp_logistic.route('/')
def sp_logistic_page():
    if not 'username' in session:
        return redirect(url_for('employees.login'))

    return render_template(
        utls.url_join(['sp_logistic', 'sp_logistic.html'])
    )

@sp_logistic.route('/add', methods=['GET', 'POST'])
def add():
    if not 'username' in session:
        return redirect(url_for('employees.login'))

    if request.method == 'GET':
        return render_template(
            utls.url_join(['sp_logistic', 'add.html']),
            carriers_ids = CarrierC.get_ids_names(),
            currencies_ids = CurrencyC.get_ids_names(),
            shipping_types_ids = ShippingTypeC.get_ids_names(),
            tracking_statuses_ids = TrackingStatusC.get_columns_by_col_names()
        )

    if request.method == 'POST':
        params = request.form
        result = SpLogisticC.add({
            'carrier_id' : params['carrier_id'],
            'total_cost' : params['total_cost'],
            'curr_id' : params['curr_id'],
            'shipping_type_id' : params['shipping_type_id'],
            'tr_number' : params['tr_number'],
            'tr_status_id' : params['tr_status_id'],
            'shipped_date' : params['shipped_date'],
            'delivered_date' : params['delivered_date'],
            'comment' : params['comment'],
            'add_emp_id' : session['employee']['id'],
            'modify_emp_id' : session['employee']['id']
        })

        if result['success']:
            return redirect(url_for('sp_logistic.all'))

        return result


@sp_logistic.route('/get/<int:shipment_id>')
def get(shipment_id):
    if not 'username' in session:
        return redirect(url_for('employees.login'))

    sp_logistic_info = SpLogisticC.get(shipment_id)

    if len(sp_logistic_info['data']) > 0:

        return render_template(
            utls.url_join(['sp_logistic', 'get.html']),
            sp_logistic_info = sp_logistic_info,
            carrier_name = CarrierC.get(sp_logistic_info['data']['carrier_id']),
            currency_name = CurrencyC.get(sp_logistic_info['data']['curr_id']),
            shipping_type_name = ShippingTypeC.get(sp_logistic_info['data']['shipping_type_id']),
            tracking_status_name = TrackingStatusC.get(sp_logistic_info['data']['tr_status_id'])
        )

    return redirect(url_for('sp_logistic.all'))


@sp_logistic.route('/all')
def all():
    if not 'username' in session:
        return redirect(url_for('employees.login'))

    sp_logistics = SpLogisticC.get_all()

    if sp_logistics['success']:
        if len(sp_logistics['data']) > 0:
            return render_template(
                utls.url_join(['sp_logistic', 'all.html']),
                sp_logistics = sp_logistics,
                carriers_ids = CarrierC.get_names_by_ids(sp_logistics['data']['carrier_id']),
                currencies_ids = CurrencyC.get_names_by_ids(sp_logistics['data']['curr_id']),
                shipping_types_ids = ShippingTypeC.get_names_by_ids(sp_logistics['data']['shipping_type_id']),
                tracking_statuses_ids = TrackingStatusC.get_names_by_ids(sp_logistics['data']['tr_status_id'])
            )

        return render_template(utls.url_join(['sp_logistic', 'all.html']),
            sp_logistics = sp_logistics
        )

    return redirect(url_for('core.index'))            # TODO later!!!!


@sp_logistic.route('/update/<int:shipment_id>', methods=['GET', 'POST'])
def update(shipment_id):
    if not 'username' in session:
        return redirect(url_for('employees.login'))

    if request.method == 'GET':
        sp_logistic_info = SpLogisticC.get(shipment_id)

        if len(sp_logistic_info['data']) > 0:

            return render_template(
                utls.url_join(['sp_logistic', 'update.html']),  
                sp_logistic_info = sp_logistic_info,
                carrier_name = CarrierC.get(sp_logistic_info['data']['carrier_id']),
                currency_name = CurrencyC.get(sp_logistic_info['data']['curr_id']),
                shipping_type_name = ShippingTypeC.get(sp_logistic_info['data']['shipping_type_id']),
                tracking_statuses_ids = TrackingStatusC.get_columns_by_col_names()
            )

        return redirect(url_for('sp_logistic.all'))

    if request.method == 'POST':
        params = request.form
        result = SpLogisticC.update({
            'tr_status_id' : params['tr_status_id'],
            'delivered_date' : params['delivered_date'],
            'comment' : params['comment'],
            'modify_emp_id' : session['employee']['id'],
            'shipment_id' : shipment_id
        })

        if result['success']:
            return redirect(url_for('sp_logistic.all'))

        return result


@sp_logistic.route('/delete/<int:shipment_id>', methods=['DELETE'])
def delete(shipment_id):
    if not 'username' in session:
        return redirect(url_for('employees.login'))

    return SpLogisticC.delete(shipment_id)

client_server_channel/templates/sp_logistic/add.html
{% extends 'base.html' %}

{% block head %}
<title>Новая доставка заказа</title>
{{super()}}

<link rel="stylesheet" href="/static/css/sp_logistic/sp_logistic_base.css">
<link rel="stylesheet" href="/static/css/sp_logistic/add.css">


{% endblock %}

{% block body %}
{{super()}}

<div class="container-crud">
    <div class="add-container">
        <div class="add-header">
            <h3>Новая доставка заказа</h3>
        </div>

        <form id="myForm" class="add-form">

            <div class="form-control">
                <label for="carrier_id">Доставщик</label><span class="star">*</span>
                <select name="carrier_id" id="carrier_id" onchange="getTrStatusByCarrId()" required>
                    <option hidden value="" selected disabled>--Выбрать--</option>
                    {% for i in range(carriers_ids['data']['carrier_id']|length)%}
                    <option value="{{carriers_ids['data']['carrier_id'][i]}}">{{carriers_ids['data']['name'][i]}}
                    </option>
                    {%endfor%}
                </select>

                <label for="total_cost">Общая стоимость</label><span class="star">*</span>
                <input type="number" name="total_cost" id="total_cost" required
                       placeholder="Введите общая стоимость..."/>

                <label for="curr_id">Валюта</label><span class="star">*</span>
                <select name="curr_id" id="curr_id" required>
                    <option hidden value="" selected disabled>--Выбрать--</option>
                    {% for i in range(currencies_ids['data']['curr_id']|length)%}
                    <option value="{{currencies_ids['data']['curr_id'][i]}}">{{currencies_ids['data']['currency'][i]}}
                    </option>
                    {%endfor%}
                </select>
            </div>

            <div class="form-control">
                <label for="shipping_type_id">Тип доставки</label><span class="star">*</span>
                <select name="shipping_type_id" id="shipping_type_id" required>
                    <option hidden value="" selected disabled>--Выбрать--</option>
                    {% for i in range(shipping_types_ids['data']['shipping_type_id']|length)%}
                    <option value="{{shipping_types_ids['data']['shipping_type_id'][i]}}">
                        {{shipping_types_ids['data']['name'][i]}}
                    </option>
                    {%endfor%}
                </select>

                <label for="tr_number">Номер отслеживания</label><span class="star">*</span>
                <input type="text" name="tr_number" id="tr_number" required
                       placeholder="Введите номер отслеживания..."/>

                <label for="tr_status_id">Статус отслеживания</label><span class="star">*</span>
                <select name="tr_status_id" id="tr_status_id" required>
                    <option hidden id="default_status" value="" selected='selected' disabled>--Выбрать--</option>
                    {% for i in range(tracking_statuses_ids['data']['status_id']|length)%}
                    <option carrier_id="{{tracking_statuses_ids['data']['carrier_id'][i]}}"
                            value="{{tracking_statuses_ids['data']['status_id'][i]}}">
                        {{tracking_statuses_ids['data']['status'][i]}}
                    </option>
                    {%endfor%}
                </select>
            </div>

            <div class="form-control">
                <label for="shipped_date">Дата отправки</label><span class="star">*</span>
                <input type="date" name="shipped_date" id="shipped_date" required/>

                <label for="delivered_date">Дата доставки</label><span class="star">*</span>
                <input type="date" name="delivered_date" id="delivered_date" required/>

                <label for="comment">Комментарий</label>
                <textarea type="text" name="comment" id="comment"
                          placeholder="Введите комментарий..."></textarea>
            </div>

            <input type="submit" class="add-submit" value="Сохранить"/>

            <input onclick="otmenFunction()" type="button" class="add-submit2" value="Отмена"/>

        </form>
    </div>
</div>

<script src="/static/js/sp_logistic/add.js"></script>

{% endblock %}

client_server_channel/templates/sp_logistic/all.html
{% extends 'base.html' %}

{% block head %}
<title>Доставки заказов</title>
{{super()}}

<link rel="stylesheet" href="/static/css/sp_logistic/all.css">

{% endblock %}

{% block body %}
{{super()}}

<div class="add-button">
    <a class="back-button" href="{{url_for('sp_logistic.sp_logistic_page')}}">Назад</a>
    <button id="addClick">Добавить</button>
</div>
<h2 class="header-all">Доставки заказов</h2>
<div class="table">
    <table>
        <thead>

        <tr>

            <th>ИД</th>

            <th>Доставщик</th>

            <th>Валюта</th>

            <th>Тип доставки</th>

            <th>Статус отслеживания</th>

            <th>Действие</th>

        </tr>

        </thead>


        <tbody id="tBody">

        {% for i in range(sp_logistics['data']['shipment_id']|length) %}
        <tr ondblclick="getType(this)">

            <td>{{sp_logistics['data']['shipment_id'][i]}}</td>

            <td>{{carriers_ids['data'][sp_logistics['data']['carrier_id'][i]]}}</td>

            <td>{{currencies_ids['data'][sp_logistics['data']['curr_id'][i]]}}</td>

            <td>{{shipping_types_ids['data'][sp_logistics['data']['shipping_type_id'][i]]}}</td>

            <td>{{tracking_statuses_ids['data'][sp_logistics['data']['tr_status_id'][i]]}}</td>

            <td>
                <button onclick="deleteType(this)">Удалить</button>
            </td>

        </tr>
        {% endfor %}

        </tbody>

    </table>
</div>


<script src="/static/js/sp_logistic/all.js"></script>

{% endblock %}

client_server_channel/templates/sp_logistic/get.html
{% extends 'base.html' %}

{% block head %}
<title>Информация о доставке заказа</title>
{{super()}}

<link rel="stylesheet" href="/static/css/sp_logistic/sp_logistic_base.css">
<link rel="stylesheet" href="/static/css/sp_logistic/get.css">

{% endblock %}

{% block body %}
{{super()}}

<div class="container-crud">
    <div class="add-container">
        <div class="add-header">
            <h3>Информация о доставке заказа</h3>
        </div>

        <div id="myForm" class="add-form">

            <input type="hidden" id="shipment_id" value="{{sp_logistic_info['data']['shipment_id']}}">

            <div class="form-control">
                <label for="carrier_id">Доставщик</label>
                <input type="text" id="carrier_id" readonly
                       value="{{carrier_name['data']['name']}}"/>

                <label for="total_cost">Общая стоимость</label>
                <input type="number" id="total_cost" readonly
                       value="{{sp_logistic_info['data']['total_cost']}}"/>

                <label for="curr_id">Валюта</label>
                <input type="text" id="curr_id" readonly
                       value="{{currency_name['data']['currency']}}"/>

            </div>

            <div class="form-control">
                <label for="shipping_type_id">Тип доставки</label>
                <input type="text" id="shipping_type_id" readonly
                       value="{{shipping_type_name['data']['name']}}"/>

                <label for="tr_number">Номер отслеживания</label>
                <input type="text" id="tr_number" readonly
                       value="{{sp_logistic_info['data']['tr_number']}}"/>

                <label for="tr_status_id">Статус отслеживания</label>
                <input type="text" id="tr_status_id" readonly
                       value="{{tracking_status_name['data']['status']}}"/>
            </div>

            <div class="form-control">
                <label for="shipped_date">Дата отправки</label>
                <input type="date" id="shipped_date" readonly
                       value="{{sp_logistic_info['data']['shipped_date']}}"/>

                <label for="delivered_date">Дата доставки</label>
                <input type="date" id="delivered_date" readonly
                       value="{{sp_logistic_info['data']['delivered_date']}}"/>

                <label for="comment">Комментарий</label>
                <input type="text" id="comment" readonly
                       value="{{sp_logistic_info['data']['comment']}}"/>
            </div>

            <button onclick="updateSpLogistic()" class="add-submit">
                Изменить
            </button>

            <button onclick="deleteSpLogistic()" class="add-submit2">
                Удалить
            </button>

            <button onclick="otmenFunction()" class="add-submit3">
                Назад
            </button>

        </div>
    </div>
</div>

<script src="/static/js/sp_logistic/get.js"></script>

{% endblock %}

client_server_channel/templates/sp_logistic/sp_logistic.html
{% extends 'base.html' %}

{% block head %}
{{super()}}
<link rel="stylesheet" href="/static/css/sp_logistic/sp_logistic.css">
{% endblock %}

{% block body %}
{{super()}}


<div style="width: 100%; text-align: center; margin-top: 1%">
    <h1>Доставки</h1>
</div>

<div class="menu">

    <ul>
        <li><a href="{{url_for('carrier.all')}}">Доставщики запчастей</a></li>
        <li><a href="{{url_for('shipping_type.all')}}">Виды доставки</a></li>
        <li><a href="{{url_for('tracking_status.all')}}">Статусы отслеживания</a></li>
        <li><a href="{{url_for('sp_logistic.all')}}">Информация о доставке</a></li>
        <li><a href="{{url_for('employees.orders_page')}}" class="back-li">Назад</a></li>
    </ul>

</div>


<script src="/static/js/sp_logistic/sp_logistic.js"></script>
{% endblock %}

client_server_channel/templates/sp_logistic/update.html
{% extends 'base.html' %}

{% block head %}
<title>Изменить данные доставки заказа</title>
{{super()}}

<link rel="stylesheet" href="/static/css/sp_logistic/sp_logistic_base.css">
<link rel="stylesheet" href="/static/css/sp_logistic/update.css">

{% endblock %}

{% block body %}
{{super()}}

<div class="container-crud">
    <div class="add-container">
        <div class="add-header">
            <h3>Изменить данные доставки заказа</h3>
        </div>

        <form class="add-form"
              action="{{ url_for('sp_logistic.update', shipment_id=sp_logistic_info['data']['shipment_id']) }}"
              method="POST">

            <div class="form-control">

                <label for="tr_status_id">Статус отслеживания</label>
                <select name="tr_status_id" id="tr_status_id">
                    {% for i in range(tracking_statuses_ids['data']['status_id']|length)%}
                    {%if sp_logistic_info['data']['tr_status_id'] == tracking_statuses_ids['data']['status_id'][i]%}
                    <option selected value="{{tracking_statuses_ids['data']['status_id'][i]}}">
                        {{tracking_statuses_ids['data']['status'][i]}}
                    </option>
                    {%else%}
                    {%if tracking_statuses_ids['data']['carrier_id'][i] == carrier_name['data']['carrier_id'] %}
                    <option value="{{tracking_statuses_ids['data']['status_id'][i]}}">
                        {{tracking_statuses_ids['data']['status'][i]}}
                    </option>
                    {%endif%}
                    {%endif%}
                    {%endfor%}
                </select>
            </div>

            <div class="form-control">
                <label for="delivered_date">Дата доставки</label>
                <input type="date" name="delivered_date" id="delivered_date"
                       value="{{sp_logistic_info['data']['delivered_date']}}"/>
            </div>

            <div class="form-control">
                <label for="comment">Комментарий</label>
                <input type="text" name="comment" id="comment"
                       value="{{sp_logistic_info['data']['comment']}}"/>
            </div>


            <input type="submit" class="add-submit" value="Сохранить"/>

            <button type="button" onclick="otmenFunction()"
                    class="add-submit2" value="Отмена">
                Отмена
            </button>

        </form>

    </div>
</div>

<script src="/static/js/sp_logistic/update.js"></script>

{% endblock %}