client_server_channel/controls/carrier/__init__.py
from .carrier import CarrierC

client_server_channel/models/carrier/__init__.py
from .carrier import CarrierTable

client_server_channel/views/carrier/__init__.py
from .views import carrier

client_server_channel/views/carrier/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from client_server_channel.controls import CarrierC
from .. import view_utils as utls


carrier = Blueprint('carrier', __name__, url_prefix='/carrier')


@carrier.route('/add', methods=['GET', 'POST'])
def add():
    if not 'username' in session:
        return redirect(url_for('employees.login'))

    if request.method == 'GET':
        return render_template(
            utls.url_join(['carrier', 'add.html'])
        )

    if request.method == 'POST':
        params = request.form
        result = CarrierC.add({
            'name' : params['name'],
            'address_1' : params['address_1'],
            'address_2' : params['address_2'],
            'city' : params['city'],
            'country' : params['country'],
            'zipcode' : params['zipcode'],
            'phone' : params['phone'],
            'email' : params['email'],
            'website' : params['website'],
            'add_emp_id' : session['employee']['id'],
            'modify_emp_id' : session['employee']['id']
        })

        if result['success']:
            return redirect(url_for('carrier.all'))

        return result


@carrier.route('/get/<int:carrier_id>')
def get(carrier_id):
    if not 'username' in session:
        return redirect(url_for('employees.login'))

    carrier_info = CarrierC.get(carrier_id)

    if len(carrier_info['data']) > 0:

        return render_template(
            utls.url_join(['carrier', 'get.html']),
            carrier_info = carrier_info
        )

    return redirect(url_for('carrier.all'))


@carrier.route('/all')
def all():
    if not 'username' in session:
        return redirect(url_for('employees.login'))

    carriers = CarrierC.get_all()

    if carriers['success']:

        return render_template(
            utls.url_join(['carrier', 'all.html']),
            carriers = carriers
        )
        
        
    return redirect(url_for('core.index'))            # TODO later!!!!


@carrier.route('/update/<int:carrier_id>', methods=['GET', 'POST'])
def update(carrier_id):
    if not 'username' in session:
        return redirect(url_for('employees.login'))

    if request.method == 'GET':
        carrier_info = CarrierC.get(carrier_id)

        if len(carrier_info['data']) > 0:

            return render_template(
                utls.url_join(['carrier', 'update.html']),  
                carrier_info = carrier_info
            )

        return redirect(url_for('carrier.all'))

    if request.method == 'POST':
        params = request.form
        result = CarrierC.update({
            'address_1' : params['address_1'],
            'address_2' : params['address_2'],
            'city' : params['city'],
            'country' : params['country'],
            'zipcode' : params['zipcode'],
            'phone' : params['phone'],
            'email' : params['email'],
            'website' : params['website'],
            'modify_emp_id' : session['employee']['id'],
            'carrier_id' : carrier_id
        })

        if result['success']:
            return redirect(url_for('carrier.all'))

        return result


@carrier.route('/delete/<int:carrier_id>', methods=['DELETE'])
def delete(carrier_id):
    if not 'username' in session:
        return redirect(url_for('employees.login'))

    return CarrierC.delete(carrier_id)

client_server_channel/templates/carrier/add.html
{% extends 'base.html' %}

{% block head %}
<title>Новый доставщик</title>
{{super()}}


<link rel="stylesheet" href="/static/css/carrier/carrier_base.css">
<link rel="stylesheet" href="/static/css/carrier/add.css">


{% endblock %}

{% block body %}
{{super()}}

<div class="container-crud">
    <div class="add-container">

        <div class="add-header">
            <h3>Новый доставщик</h3>
        </div>

        <form id="myForm" class="add-form" action="{{url_for('carrier.add')}}" method="POST">

            <div class="form-control">

                <label for="name">Название</label>
                <input type="text" name="name" placeholder="Введите название..." id="name" required/>

                <label for="address_1">Адрес</label>
                <input type="text" name="address_1" id="address_1" placeholder="Введите адрес 1..." required/>

                <label for="address_2">Адрес (необезательно)</label>
                <input type="text" name="address_2" id="address_2" placeholder="Введите адрес 2..."/>

            </div>

            <div class="form-control">

                <label for="city">Город</label>
                <input type="text" name="city" id="city" placeholder="Введите город..."/>

                <label for="country">Страна</label>
                <input type="text" name="country" id="country" placeholder="Введите страну..."/>

                <label for="zipcode">Почтовый индекс</label>
                <input type="text" name="zipcode" id="zipcode" placeholder="Введите индекс..."/>

            </div>

            <div class="form-control">

                <label for="phone">Телефон</label>
                <input type="text" name="phone" id="phone" placeholder="Введите телефон..."/>

                <label for="email">Электронная почта</label>
                <input type="text" name="email" id="email" placeholder="Введите электронную почту..."/>

                <label for="website">Сайт</label>
                <input type="text" name="website" id="website" placeholder="Введите сайт..."/>

            </div>


            <input type="submit" class="add-submit" value="Сохранить"/>

            <input onclick="otmenFunction()" type="button" class="add-submit2" value="Отмена"/>

        </form>

    </div>
</div>


<script src="/static/js/carrier/add.js"></script>

{% endblock %}

client_server_channel/templates/carrier/all.html
{% extends 'base.html' %}

{% block head %}
<title>Доставщики</title>
{{super()}}

<link rel="stylesheet" href="/static/css/carrier/all.css">

{% endblock %}

{% block body %}
{{super()}}

<div class="add-button">
    <a class="back-button" href="{{url_for('sp_logistic.sp_logistic_page')}}">Назад</a>
    <button id="addClick">Добавить</button>
</div>
<h2 class="header-all">Доставщики</h2>
<div class="table">
    <table>

        <thead>
        <tr>
            <th class="hidden">ИД</th>

            <th>Название</th>

            <th>Телефон</th>

            <th>Электронная почта</th>

            <th>Действие</th>

        </tr>
        </thead>

        <tbody id="tbody">
        {%for i in range(carriers['data']['carrier_id']|length)%}
        <tr ondblclick="getType(this)">

            <td class="hidden">{{carriers['data']['carrier_id'][i]}}</td>

            <td>{{carriers['data']['name'][i]}}</td>

            <td>{{carriers['data']['phone'][i]}}</td>

            <td>{{carriers['data']['email'][i]}}</td>

            <td>
                <button onclick="deleteCurr(this)">Удалить</button>
            </td>

        </tr>
        {%endfor%}
        </tbody>

    </table>
</div>

<script src="/static/js/carrier/all.js"></script>

{% endblock %}

client_server_channel/templates/carrier/get.html
{% extends 'base.html' %}

{% block head %}
<title>Информация о доставщике</title>
{{super()}}

<link rel="stylesheet" href="/static/css/carrier/carrier_base.css">
<link rel="stylesheet" href="/static/css/carrier/get.css">

{% endblock %}

{% block body %}
{{super()}}

<div class="container-crud">
    <div class="add-container">

        <div class="add-header">
            <h3>Информация о доставщике</h3>
        </div>

        <div class="add-form">

            <input type="hidden" id="carrier_id" value="{{carrier_info['data']['carrier_id']}}">

            <div class="form-control">

                <label for="name">Название</label>
                <input type="text" id="name"
                       value="{{carrier_info['data']['name']}}" readonly/>

                <label for="address_1">Адрес 1</label>
                <input type="text" id="address_1"
                       value="{{carrier_info['data']['address_1']}}" readonly/>

                <label for="address_2">Адрес 2</label>
                <input type="text" id="address_2"
                       value="{{carrier_info['data']['address_2']}}" readonly/>

            </div>

            <div class="form-control">

                <label for="city">Город</label>
                <input type="text" id="city"
                       value="{{carrier_info['data']['city']}}" readonly/>

                <label for="country">Страна</label>
                <input type="text" id="country"
                       value="{{carrier_info['data']['country']}}" readonly/>

                <label for="zipcode">Почтовый индекс</label>
                <input type="text" id="zipcode"
                       value="{{carrier_info['data']['zipcode']}}" readonly/>

            </div>

            <div class="form-control">

                <label for="phone">Телефон</label>
                <input type="text" id="phone"
                       value="{{carrier_info['data']['phone']}}" readonly/>

                <label for="email">Электронная почта</label>
                <input type="text" id="email"
                       value="{{carrier_info['data']['email']}}" readonly/>

                <label for="website">Сайт</label>
                <input type="text" id="website"
                       value="{{carrier_info['data']['website']}}" readonly/>

            </div>

            <button type="button" onclick="updateCarr()" class="add-submit">
                Изменить
            </button>

            <button onclick="deleteCarr()" class="add-submit2">
                Удалить
            </button>

            <button onclick="otmenFunction()" class="add-submit3">
                Назад
            </button>
        </div>

    </div>
</div>

<script src="/static/js/carrier/get.js"></script>

{% endblock %}

client_server_channel/templates/carrier/update.html
{% extends 'base.html' %}

{% block head %}
<title>Изменить данные доставщика</title>
{{super()}}

<link rel="stylesheet" href="/static/css/carrier/carrier_base.css">
<link rel="stylesheet" href="/static/css/carrier/update.css">

{% endblock %}

{% block body %}
{{super()}}

<div class="container-crud">
    <div class="add-container">
        <div class="add-header">
            <h3>Изменить данные доставщика</h3>
        </div>

        <form class="add-form"
              action="{{ url_for('carrier.update', carrier_id=carrier_info['data']['carrier_id']) }}"
              method="POST">

            <div class="form-control">
                <label for="address_1">Адрес 1</label>
                <input type="text" name="address_1" id="address_1"
                       value="{{carrier_info['data']['address_1']}}"/>

                <label for="address_2">Адрес 2</label>
                <input type="text" name="address_2" id="address_2"
                       value="{{carrier_info['data']['address_2']}}"/>

                <label for="city">Город</label>
                <input type="text" name="city" id="city"
                       value="{{carrier_info['data']['city']}}"/>

            </div>


            <div class="form-control">
                <label for="country">Страна</label>
                <input type="text" name="country" id="country"
                       value="{{carrier_info['data']['country']}}"/>

                <label for="zipcode">Почтовый индекс</label>
                <input type="text" name="zipcode" id="zipcode"
                       value="{{carrier_info['data']['zipcode']}}"/>

                <label for="phone">Телефон</label>
                <input type="text" name="phone" id="phone"
                       value="{{carrier_info['data']['phone']}}"/>

            </div>

            <div class="form-control">
                <label for="email">Электронная почта</label>
                <input type="text" name="email" id="email"
                       value="{{carrier_info['data']['email']}}"/>

                <label for="website">Сайт</label>
                <input type="text" name="website" id="website"
                       value="{{carrier_info['data']['website']}}"/>
            </div>


            <input type="submit" class="add-submit" value="Сохранить"/>

            <button type="button" onclick="otmenFunction()"
                    class="add-submit2" value="Отмена">
                Отмена
            </button>

        </form>

    </div>
</div>

<script src="/static/js/carrier/update.js"></script>

{% endblock %}