client_server_channel/controls/products/__init__.py
from .categories import CategoriesC
from .product_info import ProductInfoC
from .dealer import DealerC
from .product_status import ProductStatusC
from .product import ProductC
from .firmware import FirmwareC
from .product_photo import ProductPhotoC

client_server_channel/models/products/__init__.py
from .categories import CategoriesTable
from .product_info import ProductInfoTable
from .dealer import DealerTable
from .product_status import ProductStatusTable
from .product import ProductTable
from .firmware import FirmwareTable
from .product_photo import ProductPhotoTable

client_server_channel/views/clients/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from client_server_channel.controls import ClientC, SubscriptionC
import json
from .. import view_utils as utls
from .subscription import subscription
from .my_products import my_products


clients = Blueprint('clients', __name__, url_prefix='/clients')
clients.register_blueprint(subscription)
clients.register_blueprint(my_products)

@clients.route('/')
def clients_page():
	if not 'username' in session:
		return redirect(url_for('employees.login'))

	return render_template(
		utls.url_join(['clients', 'clients.html'])
	)

@clients.route('/login', methods=['GET', 'POST'])
def login():
	if 'clientname' in session:
		return redirect(url_for('core.index'))

	if request.method == 'GET':
		return render_template(
			utls.url_join(['clients', 'login.html']),
			user_exists = True,
			wrong_password = False
		)

	if request.method == 'POST':
		result = ClientC.login(
			request.form['clientname'],
			request.form['password']
		)

		if result['success']:
			if result['user_exists'] and not result['wrong_password']:
				session['clientname'] = request.form['clientname']
				session['client'] = {}
				session['client']['id'] = result['client_id']
				session['client']['first_name'] = result['first_name']

				return redirect(url_for('core.index'))

		return render_template(
			utls.url_join(['clients', 'login.html']),
			user_exists = result['user_exists'],
			wrong_password = result['wrong_password']
		)


@clients.route('/change_password', methods=['GET', 'POST'])
def change_password():

	if request.method == 'GET':
		return render_template(
			utls.url_join(['clients', 'change_password.html']),
			user_exists = True,
			wrong_password = False
		)

	if request.method == 'POST':
		result = ClientC.login(
			request.form['clientname'],
			request.form['password'],
			request.form['new_password']
		)

		if result['success']:
			if result['user_exists'] and not result['wrong_password']:
				return redirect(url_for('clients.login'))

		return render_template(
			utls.url_join(['clients', 'change_password.html']),
			user_exists = result['user_exists'],
			wrong_password = result['wrong_password']
		)


@clients.route('/logout')
def logout():
	if 'clientname' in session:
		session.pop('clientname')
		session.pop('client')

	return redirect(url_for('core.index'))


@clients.route('/register', methods=['GET', 'POST'])
def register():
	if request.method == 'GET':

		return render_template(
			utls.url_join(['clients','register.html'])
		)

	if request.method == 'POST':
		params = request.form
		result = ClientC.add({
			'first_name' : params['first_name'],
			'last_name' : params['last_name'],
			'birth_date' : params['birth_date'],
			'address_1' : params['address_1'],
			'city' : params['city'],
			'phone' : params['phone'],
			'email' : params['email'],
			'username' : params['clientname'],
			'password' : params['password']
		})

		if result['success']:
			return redirect(url_for('clients.login'))

		return result


@clients.route('/user_exists', methods=['POST'])
def user_exists():
	if request.method == 'POST':
		result = ClientC.user_exists(request.json['name'])

		return result


@clients.route('/account')
def account():
	if not 'clientname' in session:
		return redirect(url_for('clients.login'))

	return render_template(utls.url_join(['clients','account.html']),
		first_name = session['client']['first_name']
	)


@clients.route('/get/<int:client_id>')
def get(client_id):
	if not 'username' in session:
		return redirect(url_for('employees.login'))

	client_info = ClientC.get(client_id)
	
	if len(client_info['data']) > 0:
		
		return render_template(
			utls.url_join(['clients', 'get.html']),
			client_info = client_info,
			name_sub_id = SubscriptionC.get(client_info['data']['subs_id'])
		)

	return redirect(url_for('clients.account'))


@clients.route('/all')
def all():
    if not 'username' in session:
        return redirect(url_for('employees.login'))
    
    clients_info=ClientC.get_all()

    if clients_info['success']:
        if len(clients_info['data']) > 0:
            return render_template(
                utls.url_join(['clients','all.html']),
                clients_info=clients_info,
				names_ids_subs = SubscriptionC.get_names_by_ids(
                    clients_info['data']['subs_id']),
            )

        return render_template(
            utls.url_join(['clients','all.html']),
                clients_info = clients_info
        )

    return redirect(url_for('core.index'))            # TODO later!!!!


@clients.route('/update', methods=['GET', 'POST'])
def update():
	if not 'clientname' in session:
		return redirect(url_for('clients.login'))

	if request.method == 'GET':
		client_info = ClientC.get(session['client']['id'])

		if len(client_info['data']) > 0:
			return render_template(
				utls.url_join(['clients', 'update.html']),
				client_info = client_info,
			)

		return redirect(url_for('clients.account'))

	if request.method == 'POST':
		params = request.form
		result = ClientC.update({
			'first_name' : params['first_name'],
			'middle_name' : params['middle_name'],
			'last_name' : params['last_name'],
			'birth_date' : params['birth_date'],
			'address_1' : params['address_1'],
			'address_2' : params['address_2'],
			'city' : params['city'],
			'country' : params['country'],
			'zipcode' : params['zipcode'],
			'phone' : params['phone'],
			'home_phone' : params['home_phone'],
			'email' : params['email'],
			'client_id' : session['client']['id']
		})

		if result['success']:
			return redirect(url_for('clients.account'))

		return result


@clients.route('/delete', methods=['DELETE'])
def delete():
	if not 'clientname' in session:
		return redirect(url_for('clients.login'))

	return ClientC.delete(session['client']['id'])

client_server_channel/views/products/__init__.py
from .views import products

client_server_channel/views/products/views.py
from flask import Blueprint, render_template, request, url_for, redirect, session
from client_server_channel.controls import (ProductC, ProductInfoC, ProductPhotoC,
						DealerC, ClientC, FirmwareC, ProductStatusC)
from .. import view_utils as utls
from .category import category
from .product_info import product_info
from .dealer import dealer
from .status import status
from .firmware import firmware
from .product_photo import product_photo
# dushanbagacha commit

products = Blueprint('products', __name__, url_prefix='/products')
products.register_blueprint(category)
products.register_blueprint(product_info)
products.register_blueprint(dealer)
products.register_blueprint(status)
products.register_blueprint(firmware)
products.register_blueprint(product_photo)

@products.route('/')
def products_page():
	if not 'username' in session:
		return redirect(url_for('employees.login'))

	return render_template(
		utls.url_join(['products', 'products.html'])
	)

@products.route('/products')
def product_list():
	return render_template(utls.url_join(['products','products.html']))


@products.route('/product/<int:pid>')
def product_page(pid):
	return render_template(utls.url_join(['products','product.html']))


@products.route('/add', methods=['GET', 'POST'])
def add():
	if not 'username' in session:
		return redirect(url_for('employees.login'))

	if request.method == 'GET':

		return render_template(
			utls.url_join(['products', 'add.html']),
			products_ids = ProductInfoC.get_ids_names(),
			dealers_ids = DealerC.get_ids_names(),
			firmwares_ids = FirmwareC.get_ids_names(),
			status_ids = ProductStatusC.get_ids_names()
		)

	if request.method == 'POST':
		params = request.form
		result = ProductC.add({
			'product_id' : params['product_id'],
			'mac_address' : params['mac_address'],
			'dealer_id' : params['dealer_id'],
			'manufactured_date' : params['manufactured_date'],
			'firmware_id' : params['fw_id'],
			'status_id' : params['status_id'],
			'resp_emp_id' : session['employee']['id'],
			'add_emp_id' : session['employee']['id'],
			'modify_emp_id' : session['employee']['id']
		})

		if result['success']:
			return redirect(url_for('products.all'))

		return result


@products.route('/get/<serial_num>')
def get(serial_num):
	if not 'username' in session:
		return redirect(url_for('employees.login'))

	product_info = ProductC.get(serial_num)
	
	if len(product_info['data']) > 0:
		
		return render_template(
			utls.url_join(['products', 'get.html']),
			product_info = product_info,
			product_name = ProductInfoC.get(product_info['data']['product_id']),
			dealer_name = DealerC.get(product_info['data']['dealer_id']),
			client_name = ClientC.get(product_info['data']['client_id']),
			firmware_name = FirmwareC.get(product_info['data']['firmware_id']),
			status_name = ProductStatusC.get(product_info['data']['status_id']),
			product_photo = ProductPhotoC.get_by_product_id(product_info['data']['product_id'])
		)

	return redirect(url_for('products.all'))


@products.route('/all')
def all():
	if not 'username' in session:
		return redirect(url_for('employees.login'))

	products_info = ProductC.get_all()

	if products_info['success']:
		if len(products_info['data']) > 0:
			return render_template(
				utls.url_join(['products', 'all.html']),
				products_info = products_info,
				products_by_ids = ProductInfoC.get_names_by_ids(products_info['data']['product_id']),
				dealers_by_ids = DealerC.get_names_by_ids(products_info['data']['dealer_id']),
				clients_by_ids = ClientC.get_names_by_ids(products_info['data']['client_id']),
				firmwares_by_ids = FirmwareC.get_names_by_ids(products_info['data']['firmware_id']),
				status_by_ids = ProductStatusC.get_names_by_ids(products_info['data']['status_id'])
			)

		return render_template(utls.url_join(['products', 'all.html']),
			products_info = products_info
		)

	return redirect(url_for('core.index'))


@products.route('/update/<serial_num>', methods=['GET', 'POST'])
def update(serial_num):
	if not 'username' in session:
		return redirect(url_for('employees.login'))

	if request.method == 'GET':
		product_info = ProductC.get(serial_num)
	
		if len(product_info['data']) > 0:
			return render_template(
				utls.url_join(['products', 'update.html']),
				product_info = product_info,
				dealers_ids = DealerC.get_ids_names(),
				status_ids = ProductStatusC.get_ids_names(),
				product_name = ProductInfoC.get(product_info['data']['product_id']),
				firmwares_ids = FirmwareC.get(product_info['data']['firmware_id']),
			)

		return redirect(url_for('products.all'))

	if request.method == 'POST':
		params = request.form
		result = ProductC.update({
			'dealer_id' : params['dealer_id'],
			'resp_emp_id' : session['employee']['id'],
			'status_id' : params['status_id'],
			'modify_emp_id' : session['employee']['id'],
			'serial_num' : serial_num
		})

		if result['success']:
			return redirect(url_for('products.all'))

		return result


@products.route('/delete/<serial_num>', methods=['DELETE'])
def delete(serial_num):
	if not 'username' in session:
		return redirect(url_for('employees.login'))

	return ProductC.delete(serial_num)

client_server_channel/templates/products/product_info/add.html
{% extends 'base.html' %}

{% block head %}
<title>Информация о продукте</title>
{{super()}}

<link rel="stylesheet" href="/static/css/products/product_info/add.css">


{% endblock %}

{% block body %}
{{super()}}

<div class="container-crud">
    <div class="add-container">
        <div class="add-header">
            <h3>Информация о продукте</h3>
        </div>

        <form id="myForm" class="add-form">
            <div class="form-control">

                <label for="name">Название</label><span class="star">*</span>
                <input type="text" placeholder="Введите название..." id="name" required/>

                <label for="model">Модель</label><span class="star">*</span>
                <input type="text" id="model" placeholder="Введите модель..." required/>

                <label for="prefix">Префикс</label><span class="star">*</span>
                <input type="text" id="prefix" placeholder="Введите префикс..." required/>

                <label for="device_type">Тип Устройства</label><span class="star">*</span>
                <select id="device_type" required>
                    <option hidden value="" selected disabled>--Выбрать--</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>

                <label for="cat_id">Категория</label><span class="star">*</span>
                <select id="cat_id" required>
                    <option hidden value="" selected disabled>--Выбрать--</option>
                    {% for i in range(ids_names['data']['category_id']|length)%}
                    <option value="{{ids_names['data']['category_id'][i]}}">{{ids_names['data']['name'][i]}}</option>
                    {%endfor%}
                </select>
            </div>


            <div class="form-control">

                <label for="other_photos">Фото</label>
                <input type="file" id="other_photos" onchange="set_other_photos(this)" multiple accept="image/*"
                       style="display: none"/>
                <button type="button" id="addPhoto">Добавить фото</button>

                <label for="div_main_photo">Главное фото</label>
                <div id="div_main_photo">

                </div>

                <label for="div_other_photos">Другие фотографий</label>
                <div id="div_other_photos">

                </div>

            </div>

            <div class="form-control form-control2">
                <label for="desc">Описания</label>
                <textarea type="text" id="desc" class="desc"></textarea>
            </div>


            <input type="button" class="add-submit" onclick="addForm()" value="Сохранить"/>
            <input type="button" onclick="otmenFunction()" class="add-submit2" value="Отмена"/>
        </form>
    </div>
</div>

<script src="/static/js/products/product_info/add.js"></script>

{% endblock %}

client_server_channel/templates/products/product_info/all.html
{% extends 'base.html' %}

{% block head %}
<title>Информация о продуктов</title>
{{super()}}

<link rel="stylesheet" href="/static/css/products/product_info/all.css">

{% endblock %}

{% block body %}
{{super()}}

<div class="add-button">
    <a class="back-button" href="{{url_for('products.products_page')}}">Назад</a>
    <button id="addClick">Добавить</button>
</div>
<h2 class="header-all">Информация о продуктов</h2>
<div class="table">
    <table>
        <thead>

        <tr>

            <th class="hidden">ИД</th>

            <th>Название</th>

            <th>Действие</th>

        </tr>

        </thead>


        <tbody id="tBody">

        {% for i in range(products_info['data']['product_id']|length) %}
        <tr ondblclick="getType(this)">

            <td class="hidden">{{products_info['data']['product_id'][i]}}</td>

            <td>{{products_info['data']['name'][i]}}</td>

            <td>
                <button onclick="deleteType(this)">Удалить</button>
            </td>

        </tr>
        {% endfor %}

        </tbody>

    </table>
</div>

<script src="/static/js/products/product_info/all.js"></script>

{% endblock %}

client_server_channel/templates/products/product_info/get.html
{% extends 'base.html' %}

{% block head %}
<title>Информация о продукте</title>
{{super()}}

<link rel="stylesheet" href="/static/css/products/product_info/get.css">

{% endblock %}

{% block body %}
{{super()}}

<div class="container">

    <div class="header">
        <h3>Информация о продукте</h3>
    </div>

    <div class="form">

        <input id="product_id" type="hidden" value="{{product_info['data']['product_id']}}">

        <div class="form-control">
            <label for="name">Название</label>
            <input type="text" name="name"
                   value="{{product_info['data']['name']}}" id="name" readonly/>

            <label for="model">Модель</label>
            <input name="model" id="model"
                   readonly value="{{product_info['data']['model']}}"/>

            <label for="parent_id">Категория</label>
            <input type="text" name="parent_id"
                   value="{{id_name['data']['name']}}" id="parent_id" readonly/>
        </div>

        <div class="product-photo-label" for="{{product_photo['data']['photo_id'][i]}}">Фото</div>
        <div class="full-product-photo">
            {% for i in range(product_photo['data']['photo_id']|length) %}
            <div class="product-photo" style="display: flex">
                <img id="{{product_photo['data']['photo_id'][i]}}" width="100%"
                     src="{{product_photo['data']['small_photo'][i]}}"/>
            </div>
            {% endfor %}
        </div>

        <div class="buttons-div-get">
            <button type="button" onclick="updateProduct()" class="add-type-submit">
                Изменить
            </button>

            <button type="button" onclick="deleteProduct()" class="add-type-submit2">
                Удалить
            </button>

            <button type="button" onclick="otmenFunction()" class="add-type-submit3">
                Назад
            </button>
        </div>
    </div>

</div>


<script src="/static/js/products/product_info/get.js"></script>

{% endblock %}

client_server_channel/templates/products/product_info/get_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fido Electronics</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="stylesheet" href="/static/css/products/product_info/get_info.css">


    {% endblock %}
</head>
<body class="background-color">
{% block body %}

<div class="fixed">
    <div>
        <a href="{{url_for('core.index')}}">
            <button type="button" class="glavni-stranisa"><span style="color: #FF7F27;">Fido</span><p><span style="color: #6771ff;">Electronics</span></p></button>
        </a>
    </div>

    <a href="{{url_for('clients.logout')}}">
        <button type="button" class="glavni-stranisa viyti">Выйти</button>
    </a>
</div>

<main>
    <div class="main-cases">
        <p style="font-size: 28px; font-weight: bold">{{get_info['data']['name'][0]}}</p>
    </div>

    <section>

        <div style="width: 100%;">
            <ul class="sm-photo-ul">
                {% for i in range(get_info['data']['main_photo']|length)%}
                <li class="sm-photo-li active" id="sm_photo_li">
                    <img src="{{get_info['data']['sm_photo'][i]}}" id="smPhoto" alt="sm_img">
                </li>
                {%endfor%}
            </ul>
        </div>

        <div class="full-org-photo-div">
            {%for i in range(get_info['data']['org_photo']|length)%}
            <div class="org-photo-div active1" id="org_photo_div">
                <div class="org-img">
                    <img src="{{get_info['data']['org_photo'][i]}}" id="orgPhoto" alt="org_img">
                </div>
            </div>
            {%endfor%}
        </div>

        <div class="full-product-name-div">
            <div class="product-name-div">
                <div class="product-name">
                    {% if get_info['data']['name'][0]: %}
                    <h4>Названия продукта: <span>{{get_info['data']['name'][0]}}</span></h4>
                    <h4>Модель: <span>{{get_info['data']['model'][0]}}</span></h4>
                    <h4>Цена:<span> 100 ming so'm</span></h4>
                    <h4>Описание: <span
                            style="padding: 5px; text-align: justify;">{{get_info['data']['description'][0]}}</span></h4>

                    {%endif%}
                </div>
            </div>
        </div>

    </section>

</main>

<div class="information1">

    <div class="img-information1">
        {%for i in range(get_info['data']['org_photo']|length)%}
        <div class="img">
                    <img src="{{get_info['data']['org_photo'][i]}}" alt="org_img">
        </div>
        {%endfor%}
    </div>

</div>

{% endblock %}

<script src="/static/js/base.js"></script>
<script src="/static/js/products/product_info/get_info.js"></script>
</body>
</html>

client_server_channel/templates/products/product_info/update.html
{% extends 'base.html' %}

{% block head %}
<title>Изменить данные продукта</title>
{{super()}}
<link rel="stylesheet" href="/static/css/products/product_info/update.css">
{% endblock %}

{% block body %}
{{super()}}

<div class="add-container">

    <div class="add-header">
        <h3>Изменить данные продукта</h3>
    </div>

    <div class="add-form">
        <div class="add-photo-div">
            <input type="file" id="fileElem" multiple style="display: none" onchange="set_other_photos(this)"
                   accept="image/*">
            <button type="button" id="fileSelect">Добавить фото</button>
            <button type="button" id="" onclick="addPhoto()">Сохранить фото</button>
            <button type="button" class="add-submit" onclick="addForm()">Сохранить описание</button>
            <button type="button" onclick="otmenFunction()" class="add-submit2">Отмена</button>
        </div>

        <div class="form-control">
            {%for i in range(product_photos['data']['main_photo']|length)%}
            {%if product_photos['data']['main_photo'][i] == True:%}
            <div class="main-photo-div">
                <div class="main-photo-label">Главное фото</div>
                <div id="org_photo" class="org-photo">
                    <img id="main_photo" src="{{product_photos['data']['original_photo'][i]}}" alt="mainPhoto">
                </div>
            </div>
            {%endif%}
            {%endfor%}

            <div class="desc-div">
                <label for="desc">Описание</label>
                <textarea name="desc" id="desc">{{product_info['data']['description']}}</textarea>
            </div>

        </div>

        <div class="other-photo-label">Другие фотографии</div>
        <div id="div_other_photos" class="div-other-photos">
            {%for i in range(product_photos['data']['main_photo']|length)%}
            <div class="full-div-other-photo" id="full_div_other_photo">
                <div class="div-other-photo" id="div_other_photo">
                    <img id="{{product_photos['data']['photo_id'][i]}}" class="s"
                         src="{{product_photos['data']['original_photo'][i]}}"
                         main="{{product_photos['data']['main_photo'][i]}}" onclick="changeMainPhoto(this)">
                </div>
                <button type="button" class="delete-photo" onclick="deletePhoto(this)">Удалить фото</button>
            </div>
            {%endfor%}
        </div>
    </div>
</div>


<script src="/static/js/base.js"></script>
<script src="/static/js/products/product_info/update.js"></script>
{% endblock %}